/**
 * lib/export.ts
 * Client-side export utilities for TXT and PDF formats.
 * Uses jsPDF for PDF generation.
 */

import type { SummaryResult } from "./types";

/**
 * Export summary as a plain text file and trigger browser download.
 */
export function exportAsTxt(result: SummaryResult): void {
  const content = buildTxtContent(result);
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  downloadBlob(blob, `quickclip-${sanitizeFilename(result.videoTitle)}.txt`);
}

/**
 * Export summary as a formatted PDF and trigger browser download.
 */
export async function exportAsPdf(result: SummaryResult): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const margin = 15;
  const pageWidth = doc.internal.pageSize.getWidth();
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  const addText = (
    text: string,
    fontSize: number,
    bold = false,
    color: [number, number, number] = [30, 30, 30]
  ) => {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, maxWidth);
    if (y + lines.length * fontSize * 0.4 > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      y = margin;
    }
    doc.text(lines, margin, y);
    y += lines.length * fontSize * 0.4 + 3;
  };

  const addSectionHeader = (title: string) => {
    y += 4;
    addText(title, 13, true, [79, 70, 229]); // indigo
    y += 1;
  };

  const addDivider = () => {
    doc.setDrawColor(200, 200, 220);
    doc.line(margin, y, pageWidth - margin, y);
    y += 5;
  };

  // Header
  addText("QuickClip Summary", 20, true, [79, 70, 229]);
  addText(result.videoTitle, 14, true);
  addText(
    `Summary Length: ${result.summaryLength.charAt(0).toUpperCase() + result.summaryLength.slice(1)}`,
    10,
    false,
    [100, 100, 100]
  );
  addText(`Source: ${result.videoUrl}`, 9, false, [120, 120, 180]);
  addDivider();

  // Summary
  addSectionHeader("📄 Summary");
  addText(result.overallSummary, 10);

  // Key Points
  addSectionHeader("✅ Key Points");
  result.keyPoints.forEach((point, i) => {
    addText(`${i + 1}. ${point}`, 10);
  });

  // Timestamps
  addSectionHeader("⏱ Timestamps");
  result.timestamps.forEach((ts) => {
    addText(`[${ts.time}] ${ts.label}`, 10, true);
    addText(ts.description, 10);
    y += 1;
  });

  // Quiz
  addSectionHeader("🧠 Quiz");
  result.quiz.forEach((q, i) => {
    addText(`Q${i + 1}: ${q.question}`, 10, true);
    q.options.forEach((opt, j) => {
      const isCorrect = opt === q.correctAnswer;
      addText(`  ${["A", "B", "C", "D"][j]}. ${opt}${isCorrect ? "  ✓" : ""}`, 10, isCorrect, isCorrect ? [34, 197, 94] : [60, 60, 60]);
    });
    addText(`Explanation: ${q.explanation}`, 9, false, [120, 120, 120]);
    y += 2;
  });

  // Footer
  y = doc.internal.pageSize.getHeight() - 10;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by QuickClip • quickclip.app", margin, y);

  doc.save(`quickclip-${sanitizeFilename(result.videoTitle)}.pdf`);
}

// ─── Helpers ───────────────────────────────────────────────────────────────────

function buildTxtContent(result: SummaryResult): string {
  const lines: string[] = [
    "╔══════════════════════════════════════╗",
    "║         QUICKCLIP SUMMARY            ║",
    "╚══════════════════════════════════════╝",
    "",
    `Video: ${result.videoTitle}`,
    `URL: ${result.videoUrl}`,
    `Summary Length: ${result.summaryLength}`,
    `Generated by QuickClip`,
    "",
    "─────────────────────────────────────",
    "SUMMARY",
    "─────────────────────────────────────",
    result.overallSummary,
    "",
    "─────────────────────────────────────",
    "KEY POINTS",
    "─────────────────────────────────────",
    ...result.keyPoints.map((p, i) => `${i + 1}. ${p}`),
    "",
    "─────────────────────────────────────",
    "TIMESTAMPS",
    "─────────────────────────────────────",
    ...result.timestamps.map(
      (t) => `[${t.time}] ${t.label}\n         ${t.description}`
    ),
    "",
    "─────────────────────────────────────",
    "QUIZ",
    "─────────────────────────────────────",
    ...result.quiz.flatMap((q, i) => [
      `Q${i + 1}: ${q.question}`,
      ...q.options.map(
        (opt, j) =>
          `  ${["A", "B", "C", "D"][j]}. ${opt}${opt === q.correctAnswer ? " [CORRECT]" : ""}`
      ),
      `   Explanation: ${q.explanation}`,
      "",
    ]),
  ];

  return lines.join("\n");
}

function sanitizeFilename(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 50);
}

function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
